### ISSUE TITLE
Issue with ordering of icons in sprite

### ISSUE THREAD

**Issue by matt-bailey** [drdk/dr-svg-sprites#38]
I'm having trouble getting the sprite to respect the order in which I want the icons to be. I've tried specifying the files individually in `options.spriteElementPath`, I've tried numbering the original files e.g. `01-my-first-icon.svg`, `02-my-second-icon.svg` etc. I've tried filename to classname mapping using `options.map`. Nothing I try works, the icons are always added to the sprite in the same order.

Here's a sample of the generated sprite css - you can see the numbering is not respected:

```css
.svg-17-icon__instagram--12x12 {
	background-position: 0 0;
}

.svg-01-icon__arrow-left--12x12 {
	background-position: -23px 0;
}

.svg-03-icon__arrow-right--12x12 {
	background-position: -45px 0;
}
```

It wouldn't be an issue if it weren't for the fact that my local dev site and our staging site output the icons in one order, but our live site (when we run the build process) does it in a different order, meaning all the icons display incorrectly.

By the way, I'm using the [grunt task](https://github.com/drdk/grunt-dr-svg-sprites) version of this - should I post this question there instead?

Thanks. Any suggestions?
