### ISSUE TITLE
Custom path

### ISSUE THREAD

**Issue by gbrlsepulveda** [drdk/dr-svg-sprites#42]
Is there any way to pass a specific path to generated CSS?

## Example: 

**Default configuration**

``` javascript
var options = {
    spriteElementPath: "img/logos",
    spritePath: "img/sprites/logo-sprite.svg",
    cssPath: "css/logo-sprite.css"
};
```
```css
.foo { 
    background-image: url("../img/logos/bar.svg"); 
}
```

I would like to pass a custom path, something like this.

**Custom path**

``` javascript
var options = {
    spriteElementPath: "img/logos",
    spritePath: "img/sprites/logo-sprite.svg",
    cssPath: "css/logo-sprite.css",
    customCssPath: "shared/images"
};
```
``` css
.foo { 
    background-image: url("shared/images/bar.svg"); 
}
```
